# Generated by Django 6.0.5 on 2026-05-26 05:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('sap_fuel', 'SAP Fuel / Procurement'), ('utility', 'Utility Electricity'), ('travel', 'Corporate Travel')], max_length=20)),
                ('original_filename', models.CharField(max_length=500)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/')),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('flagged_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_sources', to='tenants.tenant')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'data_sources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.PositiveIntegerField()),
                ('raw_data', models.JSONField()),
                ('is_flagged', models.BooleanField(default=False)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_records', to='ingestion.datasource')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_records', to='tenants.tenant')),
            ],
            options={
                'db_table': 'raw_records',
                'ordering': ['data_source', 'row_number'],
            },
        ),
        migrations.AddIndex(
            model_name='datasource',
            index=models.Index(fields=['tenant', 'status'], name='data_source_tenant__5e2c7f_idx'),
        ),
        migrations.AddIndex(
            model_name='datasource',
            index=models.Index(fields=['tenant', 'source_type'], name='data_source_tenant__3da81f_idx'),
        ),
        migrations.AddConstraint(
            model_name='datasource',
            constraint=models.UniqueConstraint(condition=models.Q(('checksum__gt', '')), fields=('tenant', 'checksum'), name='unique_upload_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='rawrecord',
            index=models.Index(fields=['tenant', 'data_source'], name='raw_records_tenant__43c988_idx'),
        ),
        migrations.AddIndex(
            model_name='rawrecord',
            index=models.Index(fields=['tenant', 'is_flagged'], name='raw_records_tenant__33ba86_idx'),
        ),
        migrations.AddConstraint(
            model_name='rawrecord',
            constraint=models.UniqueConstraint(fields=('data_source', 'row_number'), name='unique_row_per_upload'),
        ),
    ]
