# Generated by Django 6.0.5 on 2026-05-26 05:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(max_length=20)),
                ('activity_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=500)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('unit', models.CharField(max_length=50)),
                ('co2e_kg', models.DecimalField(decimal_places=4, max_digits=15)),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1 — Direct emissions'), (2, 'Scope 2 — Purchased energy'), (3, 'Scope 3 — Value chain')])),
                ('emission_factor', models.DecimalField(decimal_places=6, help_text='Factor applied to compute co2e_kg', max_digits=15)),
                ('emission_factor_source', models.CharField(help_text="e.g. 'DEFRA 2023 — Natural Gas' or 'UK Grid Intensity Q3 2023'", max_length=200)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged — Needs Attention')], default='pending_review', max_length=20)),
                ('flag_type', models.CharField(blank=True, choices=[('missing_value', 'Missing required value'), ('out_of_range', 'Value out of plausible range'), ('unknown_unit', 'Unrecognised unit'), ('future_date', 'Activity date is in the future'), ('duplicate', 'Possible duplicate row')], max_length=30)),
                ('flag_reason', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('analyst_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_records', to=settings.AUTH_USER_MODEL)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emission_records', to='ingestion.datasource')),
                ('raw_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emission_records', to='ingestion.rawrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emission_records', to='tenants.tenant')),
            ],
            options={
                'db_table': 'emission_records',
                'ordering': ['-activity_date'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='emission_re_tenant__615123_idx'), models.Index(fields=['tenant', 'scope', 'activity_date'], name='emission_re_tenant__1d0e8d_idx'), models.Index(fields=['tenant', 'source_type'], name='emission_re_tenant__7e3b4e_idx'), models.Index(fields=['tenant', 'activity_date'], name='emission_re_tenant__8c6656_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('co2e_kg__gte', 0)), name='co2e_non_negative'), models.CheckConstraint(condition=models.Q(('scope__in', [1, 2, 3])), name='valid_ghg_scope')],
            },
        ),
    ]
