# Generated by Django 6.0.5 on 2026-05-26 05:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_email_snapshot', models.EmailField(blank=True, max_length=254)),
                ('event_type', models.CharField(choices=[('upload_started', 'Upload Started'), ('upload_completed', 'Upload Completed'), ('upload_failed', 'Upload Failed'), ('record_created', 'Emission Record Created'), ('record_flagged', 'Record Flagged'), ('record_approved', 'Record Approved'), ('record_rejected', 'Record Rejected'), ('tenant_created', 'Tenant Created'), ('user_permission_changed', 'User Permission Changed')], max_length=50)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('delta', models.JSONField(default=dict, help_text='{"before": {...}, "after": {...}}')),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'event_type'], name='audit_logs_tenant__2efd51_idx'), models.Index(fields=['tenant', 'created_at'], name='audit_logs_tenant__0b1a88_idx'), models.Index(fields=['actor'], name='audit_logs_actor_i_0badd2_idx'), models.Index(fields=['content_type', 'object_id'], name='audit_logs_content_b0ef47_idx')],
            },
        ),
    ]
